# Generated by Django 3.2 on 2021-05-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210511_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='note',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
