# Generated by Django 3.2 on 2021-05-15 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_entry_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.store'),
        ),
    ]
