# Generated by Django 3.2 on 2021-05-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210515_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
